"""added cable-calculations

Revision ID: 8bd01722609d
Revises: 4d084d4f280d
Create Date: 2025-12-03 10:44:46.813410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd01722609d'
down_revision: Union[str, Sequence[str], None] = '4d084d4f280d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cable_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('cable_type', sa.String(), nullable=False),
    sa.Column('cable_length_m', sa.Float(), nullable=False),
    sa.Column('number_of_cables', sa.Integer(), nullable=False),
    sa.Column('total_cores', sa.Integer(), nullable=False),
    sa.Column('loaded_cores', sa.Integer(), nullable=False),
    sa.Column('cross_section_l', sa.Float(), nullable=False),
    sa.Column('cross_section_pe', sa.Float(), nullable=False),
    sa.Column('laying_type', sa.String(), nullable=False),
    sa.Column('fuse_rating_a', sa.Float(), nullable=False),
    sa.Column('nominal_current_a', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cable_calculations_id'), 'cable_calculations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cable_calculations_id'), table_name='cable_calculations')
    op.drop_table('cable_calculations')
    # ### end Alembic commands ###
